### ISSUE TITLE
Switch to platform agnostic job runner instead of using npm scripts

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck#162]
Using npm scripts alone will prevent users on non Un*x like platforms to run the available scripts.

It would be best to switch to a task/job runner that integrates well with the proposed transition to lerna, see #157.

Nowadays, gulp seems to be the way to go for, after grunt was sort of discontinued.

However, with lerna in place, we might want to investigate this further, maybe we can leverage it so we can have additional tasks, e.g. clean and so on, which will then be platform agnostic.

Main reason being here that the clean target which utilises "rm" will not work on windoze.

**Comment by pana-cc** [comment]
rimraf. I had experience with grunt, it made terrible mess but it is a long story, gulp and broccoli are somewhat off for my taste. Anyway, I would be happy with any build system as long as it can be triggered by the npm scripts, e. g. npm i, npm prepare, npm test.

**Comment by silkentrance** [comment]
lerna is also a task runner, maybe we can leverage this beast...

**Comment by silkentrance** [comment]
Given lerna, see gh-157, we can introduce helper scripts that will offload the task from npm package.json scripts. These then will be platform agnostic.

**Comment by silkentrance** [comment]
@dcharbonnier I also do not like grunt 👍

**Comment by pana-cc** [comment]
I officially love lerna.

**Comment by silkentrance** [comment]
Okay, so we will instead introduce platform agnostic scripts instead. Closing now. Will make additional stories from this.
