### ISSUE TITLE
Support for Jest

### ISSUE THREAD

**Issue by lonix1** [testdeck/testdeck#163]
I have to ask a very rude question, apologies in advance.

I just discovered this testing library, and it's awesome! I miss testing this way... on Node the testing libraries are messy!

I've used `Jest` for a few weeks, and it'll take too long to convert to `mocha-typescript`. So I'll use it for new projects.

But until then, does anyone know of something similar for Jest - i.e. TypeScript decorators and OOP syntax?

Feel free to close if inappropriate, I just didn't know where else to ask. I thought you folks would know more about this than anyone else. (On StackOverflow I'll get the typical "but why would you want to do it that way?" answer.)

**Comment by silkentrance** [comment]
@lonix1 I do not find anything rude in your question. Please stop apologising :)

If you look at the Jest API then it is rather similar to the one that mocha uses, and deliberately so, to make migration from mocha and similar such tools more easier.

And while I am not a big fan of fb, I think that we would be able to provide a version of mocha-typescript, lets call it jest-typescript for now, that utilises Jest under the hood. (I know that there is ts-jest, so we need to come up with a better name.)

**Comment by lonix1** [comment]
@silkentrance Thanks!

Yes I realised after writing that Jest is built on Jasmine, which is Mocha's sibling, and has almost identical syntax.

And about `jest-typescript` - what a great idea! But wouldn't it be easier for the same library to support both? Assuming that under the hood there is sufficient overlap between mocha and jasmine, maybe it could simply be a matter of declaring type aliases (mocha or jest/jasmine) that could be used based on the developer's personal preference.

**Comment by silkentrance** [comment]
Investigating this a little further:

On first glance

- jest does not provide for a dynamic skip, so skipOnError might not be doable
- jest provides for a setTimeout, however, this is, just as in mocha, global,
  alternatively, one can override the global by passing a third argument to Lifecycle() and it() that defines the timeout
- jest's ProvidesCallback is similar to mocha's TestFunction, however, the callback is not optional, so our mileage may vary with TS static checks in place
- jest does not provide for a slow() function, so we need to drop it from the API
- retries in jest require jest-circus. Since this is a bad habit anyway, we might actually drop the retries() feature altogether

**Comment by silkentrance** [comment]
@lonix1 the problem lies in the typings. for mocha we heavily rely on mocha's typings and for jest we need to rely on jest's typings. ATM I do not see a way to provide an abstraction layer that would accommodate both.

**Comment by lonix1** [comment]
> @silkentrance wrote:
...Investigating this a little further...

...And then completely analyses it from every possible angle! :laughing: 

I became a little smarter just reading your comments. Thanks for looking into it.

It's sad that an abstraction is not possible. I guess I must convert to `mocha-typescript` as soon as possible.

**Comment by silkentrance** [comment]
@lonix1 I have not said that it would not be possible. We could always provide a second package for it. But this will require some time.

**Comment by silkentrance** [comment]
Reopening since I already started working on it :)

**Comment by lonix1** [comment]
I'm sorry for giving you work to do. (Yes yes, I know you said I must stop apologising.) It would be incredible though, Jest has ~4.7m downloads per week, you could steal some of those :)

I will be your first beta tester!

**Comment by silkentrance** [comment]
Yeah. We would not steal but be supplemental.

I got it working so far, however, jest seems to output everything on stderr, so I need to adjust the abstract base classes' test runners.

**Comment by silkentrance** [comment]
Also, the async tests will always fail, need to investigate this.

**Comment by silkentrance** [comment]
Funny with coverage

-------------------------|----------|----------|----------|----------|-------------------|
File                     |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------------------|----------|----------|----------|----------|-------------------|
All files                |    66.67 |     51.8 |    62.35 |    66.38 |                   |
 src                     |    58.01 |    46.28 |    59.74 |    58.09 |                   |
  index.js               |    58.01 |    46.28 |    59.74 |    58.09 |... 98,526,548,549 |
 test/it                 |    95.29 |    88.89 |     87.5 |    94.94 |                   |
  AbstractSuiteITBase.ts |    91.67 |    83.33 |      100 |       90 |             42,43 |
  util.ts                |    96.72 |    91.67 |    83.33 |    96.61 |            16,100 |
-------------------------|----------|----------|----------|----------|-------------------|




LOL

index.js               |    58.01 |    46.28 |    59.74 |    58.09 |... 98,526,548,549

we do not even have that many lines in our code...

**Comment by silkentrance** [comment]
I seems that by default jest will always report to stderr: https://github.com/facebook/jest/issues/5064
bull!

**Comment by silkentrance** [comment]
``this`` is always the empty object ``{}`` for both it and describe.

**Comment by silkentrance** [comment]
timeouts of 100ms are not working. it seems jest needs a higher timeout...

**Comment by silkentrance** [comment]
jest/jasmine combines multiple describes with the same name into one, mocha does not. need to adjust tests.

**Comment by silkentrance** [comment]
jest uses ○ instead of - for marking skipped tests... *sigh*

**Comment by silkentrance** [comment]
we have a problem in out suite callback, right where it traverses the prototype chain in order find inherited tests...

```
       ● CompleteTest › encountered a declaration exception

          @suite CompleteTest cannot be a subclass of @suite PartialTest.

            264 |       currentPrototype = Object.getPrototypeOf(currentPrototype);
            265 |       if (currentPrototype !== Object.prototype && currentPrototype.constructor[suiteSymbol]) {

                |               ^
            267 |       }
            268 |     }
```

**Comment by silkentrance** [comment]
got it working so far, will publish this on a branch derived from gh-157 as soon as I find the time. some tests are still failing and the overall coverage (using jest for testing) is not that good.

**Comment by lonix1** [comment]
Wow only saw this now... You've been busy. I'll try the new bits once they're available.

**Comment by silkentrance** [comment]
Current work on this can be found in branch gh-163, which is based on the work in gh-157.

See https://github.com/pana-cc/mocha-typescript/tree/gh-163

**Comment by lonix1** [comment]
I don't understand most of your comments, they are too advanced for me. :) Do you want me to test something?

**Comment by silkentrance** [comment]
@lonix1 If you like to, be my guest. However, not all has been refactored yet and the code needs to be cleaned up.

**Comment by pana-cc** [comment]
Pending functions in mocha:
```
describe("suite", function() {
  it("a test case that is not yet implemented");
});
```
Otherwise I love where this is going.

**Comment by pana-cc** [comment]
It would be awesome if this interface can be extended enough:
https://github.com/pana-cc/mocha-typescript/blob/852cedcfa5278cf895315b251abb9c32802895f9/index.ts#L6-L21
so mocha-typescript and jest-typescript provide its implementation and typings.

**Comment by silkentrance** [comment]
@pana-cc Yeah, I also thought about this, with a concrete implementation of any-typescript :grin: passing in required hooks and the sort of framework then figuring out everything by itself.

**Comment by pana-cc** [comment]
@silkentrance Is gh-163 somewhat ready for jest? Can I marge it into master? I'd like to spend some time on separating a "core" out of the mocha and jest version that would be shared and to get familiar with the new build system.

**Comment by silkentrance** [comment]
gh-163 is not ready yet. There are still some issues with deactivated/outcommented traits/decorator traits, slow for instance, since that is not being supported by jest/jasmine.

as for pending stuff, jest introduces `todo` whereas in plain jasmine this would be xit or xdescribe on the suite level.

**Comment by silkentrance** [comment]
I will still have rebase gh-163 to gh-157, since it is based on this one. maybe merge gh-157 first?

and for an overall release, all of the documentation along with package names and so on will have to be adjusted.

**Comment by silkentrance** [comment]
Instead of rebasing, which gave me a lot of conflicts, I recreated the branch.

It also addresses #174

**Comment by pana-cc** [comment]
Which is the last version of the branch now? Is it still gh-163? Can you make a PR so we can work on it together, I was looking into gh-163 earlier and it seems we can easily split the packages on:

 - @testdeck/core
 - @testdeck/mocha
 - @testdeck/jest
 - @testdeck/di-typedi

Where the core exports the test runner adapter interfaces, the dependency injection interfaces, provides the implementation for the decorators and the registerDI.

The mocha and jest will provide the adapter for the test runner to the core, and will reexport the decorators from core + will provide typescript typings, will also reexport the registerDI.

The di-typedi will depend on core to implement the custom DI, and then it can be required and provided to @testdeck/mocha or @testdeck/jest.

Tell me when I can join with this.

**Comment by silkentrance** [comment]
I did rename the existing packages to testdeck-*, but if you want to go for a scope over at npmjs, this is just fine with me, however, you need to rename the existing dependencies/packages and whatnot.

**Comment by silkentrance** [comment]
will make a PR just now

**Comment by silkentrance** [comment]
@pana-cc you are good to go, however, travis and appveyor builds are not running, why?

**Comment by silkentrance** [comment]
This will be dealt with in #181

**Comment by silkentrance** [comment]
Done.
