### ISSUE TITLE
Appveyor and TravisCI hooks no longer working

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck#176]
With the move to the testdeck organisation, the CI hooks are no longer working.

**Comment by silkentrance** [comment]
@pana-cc can you please have a look into this. it seems that all webhooks are registered to your user over at either appveyor or travis and the CIs are not granted any any access to the organisation or repositories thereof.

**Comment by silkentrance** [comment]
@pana-cc travis is working now, appveyor doesn't.

**Comment by pana-cc** [comment]
I am not used to the UI

**Comment by pana-cc** [comment]
It turns out I enabled the org but didn’t add the projects, appveyor should be good to go too

**Comment by silkentrance** [comment]
appveyor is also giving me a hard time. i cannot find the project there.

**Comment by pana-cc** [comment]
I added the projects, can you check again\

**Comment by silkentrance** [comment]
appveyor, sigh, i need to look into this.

do you have a link for the project?

**Comment by silkentrance** [comment]
ok, under https://ci.appveyor.com/project/pana-cc/testdeck i now can see the project

**Comment by silkentrance** [comment]
works for me.
