### ISSUE TITLE
Refactoring testdeck/core

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck#177]
For making testdeck more versatile and in order to leverage the need for

- duplicating code
- redoing everything from scratch for future support of other test frameworks

we need to refactor the core of testdeck to be more universal, meaning, that
the core must become agnostic to the actual test framework for which we
provide support for.

**Comment by pana-cc** [comment]
Just pushed a branch gh-177
It removed most of the mocha related things except for the skipOnError but its implementation is very mocha specific.
The next thing is to apply it into jest, it will require the public interface to be refined a little.

The more I look into this the more I think the traits should be removed. Basically if we limit the use of  `@suite` and `@test` to support only:
```
@suite class Suite {
  @test myTest() {
  }
}

@suite({ timeout: 1000, slow: 500 })
class Suite {
 @test({ timeout: 2000 }) myTest() {}
}
```

The whole "overload resolution" mechanism will become much more simple. Then the test and suite config json can be simply attached in a symbol on the constructor or method, and consumed by the "TestRunner" interface (that we'll rename...) like:
```
interface TestOptions {}
interface Framework {
  declareTest(name: string, fn: FN, config?: TestOptions);
  // ...
}
```
And @testdeck/mocha can extend the @testdeck/code.TestOptions with:
```
interface TestOption {
  timeout?: number;
  slow?: number;
}
```
While the jest will have just timeout.
That would ease the internal implementation and the numbers of overloads the mocha-typescript used to support, but will provide better intellisense, type checking, autocompletion, smart suggestions. But will be quite a breaking change :(

**Comment by silkentrance** [comment]
Well, it is a new project :smile:, should we even care about breaking changes?

**Comment by silkentrance** [comment]
> And @testdeck/mocha can extend the @testdeck/code.TestOptions with:
> 
> ```
> interface TestOption {
>   timeout?: number;
>   slow?: number;
> }
> ```

retries?: number?

**Comment by pana-cc** [comment]
The mocha-typescript has 500,000 downloads and 500 dependent projects. If we want them to move to @testdeck/mocha there better be smooth transition path.

I have a branch that you can see how things are going: `gh-177-2`
At some point I will merge it in gh-177.

Basically this is what is in the works:
1. Remove "traits", they were supposed to expose the "mocha" "this" from tests and suites to a function provided by 3rd party developers. I am not sure that ever happened. But I managed to preserve the syntax `@test("name", slow(2000))` by replacing the `...traits: Trait[]` with `...decorators: MethodDecorator[]`, the test decorator will apply all params decorators before it applies itself. So the above is identical to `@test("name") @slow(2000)`.

2. Decorators are split in "ExecutionModifiers" (@only, @pending, @skip) and "ExecutionOptions" (@timeout, @slow, @retries). Execution modifiers write an Execution that can be undefined, "only", "pending" or "skip" (pretty much like the old Mark interface) on the class or method function using a symbol. The ExecutionOption write the value using a symbol.

3. Upon execution of @suite or @test the execution modifiers and options values are collected into a simple JSON object and provided to the framework interface. That framework interface (still a TestRunner interface, but I am gonna rename it) is responsible to figure out what to do with the values.

4. I wiped out the tests, I think I moved them in the integration folder, but basically the core now can have much cleaner unit tests that will just assert the proper options are provided to the TestRunner without actually running test.

TODO: This is taking much more time than I anticipated :D

5. Narrow down the symbols for slow, timeout, execution etc. to one "setting" for which the class or method will store directly an instance of a "Test" or "Suite" class, and have the various decorator obtain that settings object and write on it directly. Move core logic from the monolithic TestClassUI for tests and suites into these two classes.

6. Unit tests.

7. Make the "-seed" submodules of @testdeck/testdeck

... Other?

Most of these refactorings are result of our communication and are influenced by your branches. :)

**Comment by silkentrance** [comment]
Sounds very good. As for unit tests, I am not so sure that we can achieve that using this approach, but I will wait until it is finished.

**Comment by silkentrance** [comment]
Can we please first release a 0.0.1 version on npm in order to claim the scope and name?

**Comment by silkentrance** [comment]
As of now testdeck has not yet been claimed but might be in the future.

**Comment by silkentrance** [comment]
This has been done and merged
