### ISSUE TITLE
We always want to be bleeding edge in our dependencies

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck#219]
In order to find issues in the integrations early, we always want to be bleeding edge in our overall dependencies, i.e. we favour "latest" in our dependencies over some specific version or range thereof.

**Comment by dcharbonnier** [comment]
add https://renovate.whitesourcesoftware.com/

**Comment by silkentrance** [comment]
@dcharbonnier  We only have dev dependencies, so I am absolutely fine with this :smile:.
