### ISSUE TITLE
[FEATURE] - Compiled sourcemaps must include original sources

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck#235]
## Testdeck Version

e.g. 0.0.5

## Testdeck Package

 - [x] all

## NodeJS Version

 - [x] does not apply

### Actual Behaviour

The compiled source maps reference the original source `../index.ts`, which will fail when debugging user code.

### Expected Behaviour

The compiled source maps must include the actual sources.

**Comment by pana-cc** [comment]
@silkentrance Could we close this as well? Now the sources are included in the package, but the package.json points to a compiled .js. The source maps for the js files point to the ts files in the package, so it should be possible to put a breakpoint in TS and debug.

**Comment by silkentrance** [comment]
yes, of course. feel free to close whatever issues you think are obsolete.

**Comment by silkentrance** [comment]
Closing since @pana-cc fixed this by integrating the sources in the distribution package.
