### ISSUE TITLE
[FEATURE] - Parameterized suites

### ISSUE THREAD

**Issue by jrumbinas** [testdeck/testdeck#237]
## Testdeck Version
0.0.6

## Description
It would be nice to support @params for suites.

## Additional info
@testdeck [Parameterized Test](https://testdeck.org/pages/guide/parametrised_tests)
mocha-typescript [Generated Suites](https://www.npmjs.com/package/mocha-typescript#generated-suites-and-tests)
JUnit [Parameterized runner](https://dzone.com/articles/junit-parameterized-test)

**Comment by silkentrance** [comment]
@jrumbinas While this would be possible, I do not see any benefit in this. As for generated suites, you can always use [nested suites](https://testdeck.org/pages/guide/nested).

Or even use factory functions to generate your so configured suites, e.g.

```
function factory(param1, param2) {
   @suite
   class ParametrisedSuite {
    //...
   }
}
```

Either way, I see more benefit in parametrising existing `@test` annotated methods of the suite class as it is more versatile.
