### ISSUE TITLE
[BUG] - "static async after" triggered before the test

### ISSUE THREAD

**Issue by xeoh** [testdeck/testdeck#239]
I know that `static async after` function is equivalent to `afterall` in jest. However, my `static async after` is being called before the test. Below is my simple test script and console output.

**`sample.test.tsx`**
```typescript
// tslint:disable: no-implicit-dependencies
import { suite, test } from "@testdeck/jest"
import puppeteer, { Browser } from "puppeteer"

@suite
class TestSuite {
	static browser: Browser

	static async before() {
		console.log("before")
		TestSuite.browser = await puppeteer.launch()
	}

	static async after() {
		console.log("after")
		await TestSuite.browser.close()
	}

	@test("test")
	async testTrue__expectTrue() {
		console.log("test")
		await new Promise((resolve) => {
			setTimeout(() => { resolve() }, 1000)
		})
		expect(true).toBe(true)
	}
}

```
**`Console output`**

```console
  console.log __test__/sample.test.tsx:10
    before

  console.log __test__/sample.test.tsx:15
    after

  console.log __test__/sample.test.tsx:21
    test

 PASS  __test__/sample.test.tsx
  TestSuite
    ✓ test (1007ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        4.217s
Ran all test suites.
```

## Testdeck Version

`0.0.6`

## Testdeck Package
 - [x] `@testdeck/jest`

## NodeJS Version
 - [x] 8

## Mocha / Jasmine / Jest Version
 - Jest: 
 - `@types/jest`: 24.0.15

### Operating System
 - [x] Mac OS X

### Actual Behaviour
console output of my test code is
```
after
before
test
```

### Expected Behaviour
console output of my test code should be
```
after
test
before
```

### Additional Information
[test repo](https://github.com/xeoh/jest-bug-report)

**Comment by silkentrance** [comment]
@xeoh very good find. and the reason for this is that

```
  afterAll(name: string, callback: core.CallbackOptionallyAsync, settings?: core.LifecycleSettings): void {
    beforeAll(callback, settings && settings.timeout);
  }
```

our wrapper for this will actually call beforeAll...

**Comment by silkentrance** [comment]
And while there is a test for that, it will not fail. Need to check this as well.

**Comment by silkentrance** [comment]
Okay, this is funny. The test uses the wrapper afterAll and all assertions are run beforeAll...

**Comment by silkentrance** [comment]
And the actual reason for the test not failing is the test uses assertDeepEqual instead of sameOrderedMembers.

**Comment by silkentrance** [comment]
While this does not affect mocha, here, the exception in the after all hook will be reported, it should also be fixed and turned into a proper test.

https://github.com/mochajs/mocha/issues/2684

The test for the Jasmine wrapper was also fixed.

**Comment by silkentrance** [comment]
https://github.com/testdeck/testdeck/pull/240

**Comment by silkentrance** [comment]
We will do a new release ASAP. ATM I am busy with work, so I will look into this at the end of the week.
