### ISSUE TITLE
[BUG] - di-typedi - dependencies not being constructed in suite

### ISSUE THREAD

**Issue by gibsonjoshua55** [testdeck/testdeck#241]
## Testdeck Version

- @testdeck/mocha: 0.0.6
- @testdeck/di-typedi: 0.0.6
- typedi: 0.8.0

## Testdeck Package

 - [ ] `@testdeck/core`
 - [ ] `@testdeck/mocha`
 - [ ] `@testdeck/jasmine`
 - [ ] `@testdeck/jest`
 - [x] `@testdeck/di-typedi`  
- [ ] unsure

## NodeJS Version

 - [ ] 11
 - [ ] 10
 - [ ] 9
 - [ ] 8
 - [x] all
 - [ ] other: 

## Mocha / Jasmine / Jest Version

 - Mocha:
 - `@types/mocha`: 5.2.7
 - Jasmine:
 - `@types/jasmine`: 
 - Jest: 
 - `@types/jest`: 

### Operating System

 - [ ] Linux
 - [x] Mac OS X
 - [ ] Windows 7
 - [ ] Windows 10
 - [ ] Other:

### Actual Behaviour

When a service is passed into the constructor of a test suite, it is not the contstructed instance of the service, it just the entire container.

### Expected Behaviour

According to the example, and typical type-di usage, the service should come into the constructor already constructed.

### Additional Information
The index file is required by `mocha.opts` and sets up the dependency injection and sets environment variables.

```
// index.ts
import 'reflect-metadata';
import '@testdeck/di-typedi';
import { config } from 'dotenv';

config();
```

```typescript
// firebase.service.ts
import * as admin from 'firebase-admin';
import { Service } from 'typedi';

@Service()
export class Firebase {
    app: admin.app.App;

    constructor() {
        console.log('firebase constructing');
        this.app = admin.initializeApp({
            projectId: process.env.PROJECT_ID
        })
    }

}
```

```typescript
// character.ts
import { suite, test } from '@testdeck/mocha';
import { assert } from 'chai';
import { Firebase } from '../../services/firebase';
import { Service } from 'typedi';

@suite()
@Service()
export class CharactersSuite {

    constructor(private readonly firebase: Firebase) {
        console.log(this.firebase);
    }

    @test
    someTest() {
        assert.ok(true);
    }
}
```

#### Output
```
> ts-mocha -p test/tsconfig.json



  CharactersSuite
ContainerInstance {
  services: [ { type: [Object] }, { type: [Function: Firebase] } ],
  id: undefined }
    ✓ someTest


  1 passing (13ms)
```

**Comment by silkentrance** [comment]
@gibsonjoshua55 Thank you, nice find!
I will try to fix that on the weekend. It has worked before :)

**Comment by silkentrance** [comment]
Sorry for the delay. I am currently moving to a different location and do not have the time for looking into this.

**Comment by silkentrance** [comment]
@gibsonjoshua55 Have you tried removing the @Service() annotation from the suite?

The problem with the annotation is that the test suite class will then be registered as a service with the container.

Also, the first parameter to the constructor will be the container itself, so that you can get services from the container without having to use the ``@Inject``` annotation or register named services with the container and so on.

See https://github.com/rosario/example-with-typedi for more information.

**Comment by silkentrance** [comment]
I just checked out test suite in packages/@testdeck/di-typedi and it works as expected.

You definitely should not annotate the test suite class with the ```@Service``` annotation unless you want to be able to inject the test suite into other clients, which would not really make any sense.
