### ISSUE TITLE
[BUG] - Premature calls to helper functions break suite creation

### ISSUE THREAD

**Issue by braaibander** [testdeck/testdeck#245]
## NodeJS Version

 - [ ] 11
 - [x] 10
 - [ ] 9
 - [ ] 8
 - [ ] all
 - [ ] other: 

## Mocha / Jasmine / Jest Version

 - Mocha: 6.2.0
 - Mocha-typescript: 1.1.17

### Operating System

 - [ ] Linux
 - [ ] Mac OS X
 - [ ] Windows 7
 - [x] Windows 10
 - [ ] Other:

### Actual Behaviour

When writing tests I commonly use a get function to fetch the object from the IMock instance. See snippet below. 
This has not caused me any issues before on version 1.1.10, but after an update to 1.1.17 this snippet will no longer run.

After some debugging I discovered that Mocha calls the get function before the `before` function is called, which obviously returns a TypeError because `this.testInstanceMock` is undefined. This happens both in 1.1.10 and 1.1.17, but the difference is that in the newest version, the exception is not caught and it breaks the suite.

### Expected Behaviour

It should either not try to run any function without a `@test` decorator, or ignore any errors that might come out of these function calls.

### Additional Information

Code snippet:
```Typescript
@suite
class BugReport {
	private testInstanceMock: Moq.IMock<AnyType>;

	public get testInstance(): AnyType{
		return this.testInstanceMock.object;
	}

	public before() {
		this.testInstanceMock = Moq.Mock.ofType(AnyType);
	}

	@test
	private constructor__ValuesSetCorrectly() {
		this.testInstance.doSomething();
	}
}
```

**Comment by braaibander** [comment]
Sorry, I think this is the wrong place to report this bug.
My appologies

**Comment by silkentrance** [comment]
Nah, you need to give us more information, this is not sufficient.

What is the mocking framework that you are using, and how do import it and also, please, give us a real code example instead of just a snippet.

TIA

**Comment by silkentrance** [comment]
And what is version 1.1.10 and 1.1.17? testdeck is currently versioned at 0.0.6!?

**Comment by silkentrance** [comment]
And why would you use the indirection of getters when you can access the private / protected properties of your concrete test suites directly? Which would be an anti pattern unless you have an abstract base class which would provide you with that property already initialised via a before hook.

**Comment by silkentrance** [comment]
@braaibander have you tried `@testdeck/mocha` yet?

**Comment by silkentrance** [comment]
Not to mention that, in your constructor, you are

```

	@test
	private constructor__ValuesSetCorrectly() {
		this.testInstance.doSomething();
	}
```

calling the getter.

Get your gears straight, man.

**Comment by braaibander** [comment]
> And what is version 1.1.10 and 1.1.17? testdeck is currently versioned at 0.0.6!?

@silkentrance This has been a bit confusing for me too I must admit, but as the report says I am using [mocha-typescript](https://www.npmjs.com/package/mocha-typescript), which npm page directly sends me to the testdeck repository. I'm not fully sure how that package is maintained, but I haven't found any indication that it has been depricated in favour of testdeck.

> Nah, you need to give us more information, this is not sufficient.
> 
> What is the mocking framework that you are using, and how do you import it and also, please, give us a real code example instead of just a snippet.
> 
> TIA
I added a full case for it:
[Sandbox.zip](https://github.com/testdeck/testdeck/files/3615448/Sandbox.zip)
npm install && npm run test will give you an error. If you change the mocha-typescript version to 1.1.10 it will work.


> And why would you use the indirection of getters when you can access the private / protected properties of your concrete test suites directly? Which would be an anti pattern unless you have an abstract base class which would provide you with that property already initialised via a before hook.
> 
> Anti pattern in the sense of KISS and YAGNI.
The case for these getters is mainly reababilty of your test code, but this issue could just as easily occur if your test cases are highly repetitive and it makes sense to lift some of that repetition into a seperate function. Regardless, this bahaviour changed quite drastically (and destructively) in what is supposed to be a minor version, so I am asuming this is a bug and not a feature.

> @braaibander have you tried @testdeck/mocha yet?
No I have not. As mentioned before, I'm not sure what the status is of the mocha-typescript package I was used to using.

**Comment by silkentrance** [comment]
@braaibander coming back to this, have you tried `@testdeck/mocha` yet?
