### ISSUE TITLE
[BUG] - Suite superclass accessors called before constructor during suite construction

### ISSUE THREAD

**Issue by rfrowe** [testdeck/testdeck#248]
## Testdeck Version

0.0.6

## Testdeck Package

 - [x] `@testdeck/core`
 - [x] `@testdeck/mocha`
 - [ ] `@testdeck/jasmine`
 - [ ] `@testdeck/jest`
 - [ ] unsure

## NodeJS Version

 - [x] 12
 - [ ] 11
 - [ ] 10
 - [ ] 9
 - [ ] 8
 - [ ] all
 - [ ] other: 

## Mocha / Jasmine / Jest Version

 - Mocha:6.2.2
 - `@types/mocha`: 5.2.7

### Operating System

 - [ ] Linux
 - [x] Mac OS X
 - [ ] Windows 7
 - [ ] Windows 10
 - [ ] Other:

### Actual Behaviour

Given the class

```typescript
class Foo {
    private readonly _strings: Set<string>;
    constructor() {
        this._strings = new Set<string>();
    }

    get strings(): string[] {
        return Array.from(this._strings)
    }
}
```

and the suite

```typescript
@suite
class FooTest extends Foo { }
```

Receive the following error:
```
TypeError: Cannot convert undefined or null to object
    at Function.from (<anonymous>)
    at FooTest.get strings [as strings]
```

### Expected Behaviour

No inherited methods of `Foo` should be executed before the constructor is called.

### Additional Information

The issue appears to be in `index.js` of `@testdeck/core` at line 101:

```
99:  while (currentPrototype !== Object.prototype) {
100:     Object.getOwnPropertyNames(currentPrototype).forEach((key) => {
101:     if (typeof prototype[key] === "function") {
```

The `prototype[key]` where `prototype` is `Foo` and `key` is `string` is calling the getter before the constructor of `Foo` has been called, resulting in a call to `Arrays.from` with an undefined argument as the field has yet to be set.

**Comment by silkentrance** [comment]
I need to investigate this. Ideally, only methods that have one of the available decorators that declare test methods should be called.

**Comment by silkentrance** [comment]
Looking at https://github.com/testdeck/testdeck/blob/7d4811a9d8bf0bdc5ea48eea8ba6af3ea0125d96/packages/%40testdeck/core/index.ts#L134

it does exactly that.

The methods, as they are declared, will be augmented with a specific symbol, and only if that symbol is there, the method will be treated as a test method.

I wonder what is going wrong here...

**Comment by silkentrance** [comment]
You are absolutely correct in your analysis. Accessing the property by name will invoke the getter. Never thought of that when implementing the recursive lookup for inherited test methods.

As a first resolve I would enclose the statement in a try/catch. After which I will look into the existing reflection API and see whether we can circumvent this rather costly operation.

**Comment by silkentrance** [comment]
This also affects the jasmine and jest package.

**Comment by silkentrance** [comment]
Finally made it work with the core test suite.

**Comment by silkentrance** [comment]
Although the typedi tests are still failing...

**Comment by silkentrance** [comment]
I will disable the di-typedi package for now, so that we can get a working PR.

**Comment by silkentrance** [comment]
https://github.com/babel/babel/issues/11441
