### ISSUE TITLE
[QUESTION] - PHP-Storm support

### ISSUE THREAD

**Issue by kevincodecookies** [testdeck/testdeck#260]
## Question

with mocha-typescript -- https://www.npmjs.com/package/mocha-typescript
i could run tests directly from PHPStorm or WebStorm.

with @testdeck/jest this is not the case.

Is Support planned for the future?

**Comment by silkentrance** [comment]
@kevincodecookies the plugin that integrates mocha-typescript is made by jetbrains. I have already looked at the code but have not yet found the time to pursue this any further.

**Comment by silkentrance** [comment]
closing as the integration of testdeck is subject to the jetbrains provided plugin.

**Comment by silkentrance** [comment]
reopening. I reckon that the might not even know about testdeck 😁

**Comment by silkentrance** [comment]
closing again, as it seems that with the latest version of WebStorm this issue has been resolved. And since jetbrains reuses code, I reckon that it will also be fixed in PhpStorm and the other IDEs as well.
