### ISSUE TITLE
[BUG] - testdeck after hooks fail due to jest/jasmine calling after hooks in their reverse order

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck#265]
## Testdeck Version

all

## Testdeck Package

 - [x] `@testdeck/core`
 - [x] `@testdeck/jasmine`
 - [x] `@testdeck/jest`

## NodeJS Version

 - [x] all

### Actual Behaviour

User defined `static after`, aka `afterAll` and instance level `after`, aka `afterEach` hooks fail due to `this` being `null` if user code tries to access the instance.

### Expected Behaviour

`this` must not be `null`.

### Additional Information

Jest and Jasmine will execute the afterAll/afterEach hooks in reverse order. `@testdeck/core` installs an additional `afterEach` hook that will tear down the instance of the test suite.
As of now, the teardown hook installed by `testdeck` will be executed first and subsequently, the user defined `static after` and `after` hooks will fail with an NPE when accessing `this` as `this` is `null`.

This requires immediate action and a new release.

A big thank you goes out to @dcharbonnier who was the only one to actually "kinda" report this bug, see #261 for more information.

**Comment by silkentrance** [comment]
NOTE: the fix for this has been tested manually using a different project I am working on. In order to provide tests for this, the existing test suites need to be refactored, which is a major undertaking and will not make it into this hotfix.

**Comment by silkentrance** [comment]
See PR #266

**Comment by silkentrance** [comment]
@dcharbonnier this has now been fixed and v0.0.8 has been released on npm.

**Comment by egor-romanov** [comment]
Hey guys, this bug is now returned in v0.2.0

in 0.1.2 everything works fine 

Thanks for your work

**Comment by silkentrance** [comment]
Jest changed its default test runner to jest-circus, see https://jestjs.io/docs/configuration#testrunner-string.

The testdeck/jest package supports the default test runner only.

jest-jasmine2 is now optional, see https://jestjs.io/blog/2021/05/25/jest-27 and currently not supported, see PR https://github.com/testdeck/testdeck/pull/293.
