### ISSUE TITLE
[QUESTION] - BeforeAll test suite setup for jest

### ISSUE THREAD

**Issue by longnguyennn** [testdeck/testdeck#273]
## Question

Hi, I just stumbled across this library and found it very interesting. However, I couldn't figure out how to instantiate class variables for a suite before running the tests. Usually that could be done using `beforeAll()` in Jest but with this library, it seems like we have to define `static before()` but then we can't initialize class variable inside a static function. Do you guys currently support this feature?

**Comment by silkentrance** [comment]
@longnguyennn Of course. ``this`` is the constructor, so you can simply declare a private static field and access this using ``this.<field>``, e.g.

```
@suite
class Suite {
    private static foo = false;

    public static before() {
       this.foo = true;
    }

    @test
    public void testing() {
       assert.ok(Suite.foo);
    }
}
```

**Comment by silkentrance** [comment]
And you can also access it using ``Suite.foo = true`` from inside the ``static before()``.

See also https://testdeck.org/pages/guide/advanced_suite#static-lifecycle-hooks---

**Comment by longnguyennn** [comment]
Thanks for the swift response. Really love what you guys are working on. Keep it up!

**Comment by silkentrance** [comment]
@longnguyennn appreciated, thank you.

**Comment by silkentrance** [comment]
@longnguyennn a new release 0.1.0 has been published.
