### ISSUE TITLE
[BUG] - Error

### ISSUE THREAD

**Issue by brianschardt** [testdeck/testdeck#275]
## Testdeck Version

Error 
```
✖ ERROR: --opts: configuring Mocha via 'mocha.opts' is DEPRECATED and no longer supported.
          Please use a configuration file instead.
/Users/brianschardt/Desktop/testdeck-mocha-seed/node_modules/yargs/yargs.js:1172
      else throw err
           ^
```

**Comment by silkentrance** [comment]
@brianschardt How about providing us with a PR for this?

**Comment by silkentrance** [comment]
@brianschardt I just tested this with the latest version of `testdeck-mocha-seed` and also the latest versions of the dependencies.
However, I am not able to reproduce the above error.

I will remove the mocha.opts and instead provide a working sample .mocharc.yaml, though.

**Comment by silkentrance** [comment]
closed by https://github.com/testdeck/testdeck/issues/275
