### ISSUE TITLE
[BUG] Can't use `static after` method without `static before`

### ISSUE THREAD

**Issue by leejh3224** [testdeck/testdeck#276]
https://github.com/testdeck/testdeck/blob/f7ec97b1aec3d053a28bd5d8ccc74180d77f21d6/packages/core/index.ts#L226

Line above causes `TypeError: Cannot use 'in' operator to search for '__testdeck_slow' in undefined` error when someone uses `static after` alone.

It should be fixed by following
```ts
// packages/core/index.ts:221
if (constructor.after) {
        if (isAsync(constructor.after)) {
          theTestUI.runner.afterAll("static after", wrap(function(done) {
            return constructor.after(done);
          }, constructor.after), theTestUI.getSettings(constructor.before)); // should be constructor.after!
        } else {
          theTestUI.runner.afterAll("static after", wrap(function() {
            return constructor.after();
          }, constructor.after), theTestUI.getSettings(constructor.before)); // should be constructor.after!
        }
      }
```

This error can easily be reproduced by following code example.

```ts
import { suite } from "@testdeck/jest"

@suite()
class HookTest {
   static after() {
      console.log("this will throw error") 
   }
}
```

Though not tested, I also opened [pull request](https://github.com/leejh3224/testdeck/pull/1/files) for this issue.

**Comment by silkentrance** [comment]
@leejh3224 Thank you very much. This bug did go undetected for a while now. Very nice find. And a very nice PR.
Let's see, how can this even be tested?

**Comment by silkentrance** [comment]
@leejh3224 

Maybe you can add the following test to test.ts? I am still trying to work out how one can add to a given PR. Did not work out for me in the past...

```
describe("testdeck", function() {
   [...]

   describe("decorators", function() {
   [...]

        it("gh-276: regression static after only must not result in error", function() {

            ui.log = LoggingClassTestUI.Log.SetupTeardown;

            assert.doesNotThrow(function() {
                @ui.suite class SomeSuite {
                    public static after() {}
                }
            });
        });
[...]
```

**Comment by leejh3224** [comment]
@silkentrance 
Added test you mentioned. It worked exactly as I expected :) Thanks for suggestion.

**Comment by silkentrance** [comment]
@leejh3224 Thank you very much. I will review the code now and merge the PR.
