### ISSUE TITLE
[QUESTION] - how can i using decorators?

### ISSUE THREAD

**Issue by yantrab** [testdeck/testdeck#278]
## Question

Hi, thanks for your package.
i trying to create mock decorator :

```
export const mock = <T>(provide: any, key: keyof T, value: any) => (target: any, propertyKey: string, descriptor: PropertyDescriptor) => {
  const originalMethod = descriptor.value;
  descriptor.value = async function(...args: any[]) {
    await diService.mock(provide, key, value);
    originalMethod.apply(this, args);
  };
};

  @test("should add token where user is valid")
  @mock<UserService>(UserService, "validateAndGetUser", { fName: "lo", lName: "asbaba" })
  async login() {
    const res = await this.app.inject({ method: "POST", url: "/auth/login" });
    expect(res.body).toBe("Hi");
  }
```
but he say that " Your test suite must contain at least one test".
it is possible to using decorators here? 
thanks

**Comment by yantrab** [comment]
`return target;` in the end solved my problem.

**Comment by silkentrance** [comment]
@yantrab any progress on this?

**Comment by silkentrance** [comment]
@yantrab what is your test suite class?

**Comment by yantrab** [comment]
Hi @silkentrance  sorry , yes, i did some hook for that but it is work and i think that it is nice to put it on decorators . 

```
/**
 *
 * @param provider the service that you want to mock
 * @param key function name
 * @param value object or function
 */
export const mock = <T, P = new (...args: any[]) => T>(
  provider: P,
  key: ClassType<P>,
  value: P extends { new (): infer R }
    ? R[keyof R] extends AnyFunc
      ? PromiseReturnType<ReturnType<R[keyof R]>> | ((...args: any[]) => PromiseReturnType<ReturnType<R[keyof R]>>)
      : any
    : any
) => (target: any, propertyKey: string, descriptor: PropertyDescriptor) => {
  const originalMethod = descriptor.value;
  target[propertyKey] = async function() {
    const temp = await diService.inject(provider);
    await diService.mock(provider, key, value);
    const result = await originalMethod.apply(this);
    diService.override((provider as any).name, temp);
    return result;
  };
  return target;
};

```
and usage example - 

```
  @test("should return mocked user")
  @mock(UserService, "validateAndGetUser", { fName: "lo", lName: "asbaba" })
  async login() {
    const res = await this.app.inject({ method: "POST", url: "/auth/login", body: { email: "a@b.c", password: "password" } } as any);
    expect(res.json()).toStrictEqual({ fName: "lo", lName: "asbaba" });
  }
```

**Comment by silkentrance** [comment]
@yantrab hm, i do not see a `@suite` decorated class. have you looked at the testdeck documentation over at testdeck.org, yet?
See http://testdeck.org/pages/guide/basics for an quick introduction.

**Comment by panayot-cankov** [comment]
The ‘@test’ will capture the method function passed to it, and later will use ‘call’ to execute it. Maybe we should instead capture its name and call it using something like ‘instance[testName]()’ to allow polymorphism (test override in derived classes) and mock to replace it here:

https://github.com/testdeck/testdeck/blob/c0466f083c9d390e2d2a43bbefa0084266a7aeb5/packages/core/index.ts#L189

As a workaround it is worth trying to reverse the order of the @test and @mock.

**Comment by silkentrance** [comment]
@pana-cc what the OP wants is to inject / mutate an existing mock with a method that returns the specified parameters.

**Comment by silkentrance** [comment]
@pana-cc the mock is async and the test is not.

**Comment by silkentrance** [comment]
so for my part, this is a won't do as one can use existing mocking frameworks and must not reinvent the wheel.

**Comment by silkentrance** [comment]
as for the order of decorators, it should be clear that the order of execution is top to bottom and that the user implementing decorators must be aware of that.

**Comment by pana-cc** [comment]
There are mutating decorators. Mutating decorators change the function that is assigned on the class prototype. Our own @test decorator is not mutating, it just writes up some metadata. The issue I am aware of, is that if a mutating decorator is applied after our @test decorator, we will write up some test metadata on a function, that is replaced by the mutating decorator with another function. So a change that I am thinking to do, when I get some available time, is to write up the metadata on the class instead of on the method function, and use the method name as a key in a dictionary to access that metadata.

**Comment by silkentrance** [comment]
@pana-cc binding that to the method name requires that

```
@foo
@test
@bar
@timeout(...)
async login() {}
```

`@foo` will return the same name as `@test` and `@bar`.

however, you cannot ever control the outer decorators, so they might return a different value for the ``function name``.

even the inside decorators might return a different function name.

so there should be some convention in place?

**Comment by silkentrance** [comment]
and while the outer decorators are not actually of our concern, the inner decorators are and they must always return the original method name, whether adding meta data or replacing the underlying function.

**Comment by pana-cc** [comment]
The decorators can provide a function with a changed name, but the key I think to use is the one passed to the decorator (it is in the signature ‘(target: any, propertyKey: string, descriptor: PropertyDescriptor)’) and the decorators can’t change that. It also works with computed method names and symbols.

**Comment by silkentrance** [comment]
@pana-cc So that would be another topic and we can close this as won't fix as existing mocking frameworks will do the trick?

**Comment by pana-cc** [comment]
Yes. But the initial question is “how can use decorator” and the decorator is “mock” by coincidence. The problem with it is it is mutating decorator.

If you want to close this issue, I am ok with that. But also if we don’t over fixate on the mocking part it is pretty well defined.

**Comment by silkentrance** [comment]
@pana-cc 

I think that we need to communicate to the users on where to place their decorators and for what purpose.
https://github.com/testdeck/testdeck/issues/278#issuecomment-988204735

And users who author decorators are well aware of the order in which they are being executed.

@yantrab needs to understand existing mocking frameworks first and how to utilize them and also on how to inject so mocked up services into his or her application under test.

**Comment by silkentrance** [comment]
Okay closing as won't fix as the user did not understand the basic principles of mock testing while unwilling to use an existing mocking framework such as https://github.com/NagRock/ts-mockito#basics.
