### ISSUE TITLE
[FEATURE] - Support Nest.js

### ISSUE THREAD

**Issue by stevefan1999-personal** [testdeck/testdeck#281]
## Testdeck Version

latest

## Description

Let us inject nest.js services into suites, should be similar to how you deal it in TypeDI

## Workaround
Since `Test.createTestingModule<T>().compile()` is an async function/returns a Promise, we cannot directly modify `DependencyInjectionSystem.create` to return Promise -- since this mean we need to virally insert async to all the relevant functions, it will eventually come down to setup instance, and this interfere with the order of the suite setup calls (so before/after/beforeEach/afterEach order is not consistent and the value of instance is not immediately available)

There is two approaches to deal with this, the easiest way is to manually supply `async before()` and do module resolution there instead like this:
```ts
@suite
class PrismaServiceSpec {
  constructor(private service: PrismaService) {}

  async beforeEach() {
    const container: TestingModule = await Test.createTestingModule({
      providers: [PrismaService],
    }).compile();
    this.service = container.get(PrismaService);
  }

  @test
  'should be defined'() {
    expect(this.service).toBeDefined();
  }
}
```
but it defeats the whole purpose of constructor injection.

The second approach is to leverage top level await:
```ts
const container: TestingModule = await Test.createTestingModule({
  providers: [PrismaService],
}).compile();

registerDI({
  create<T>(cls: TestClass<T>): T {
    return container.get<T>(cls);
  },
  handles: <T>(cls: TestClass<T>): boolean => true,
});

@suite
class PrismaServiceSpec {
  constructor(private service: PrismaService) {}

  @test
  'should be defined'() {
    expect(this.service).toBeDefined();
  }
}
```
which also unfortunately not available in the current state of ECMAScript.

**Comment by silkentrance** [comment]
As documented in https://docs.nestjs.com/fundamentals/testing#testing-utilities the beforeEach approach is the actual approach taken by the NestJS framework.

However, with testdeck, you can easily make this a beforeAll and implement that in for example an abstract base class from which your concrete suites derive from, e.g. 

```
abstract class TestSuiteBaseWithContainer {
   public static container: TestingModule;

   @before
   static async beforeAll() {
     this.container = await Test.createTestingModule({
        controllers: [CatsController],
        providers: [CatsService],
      }).compile();
   }
}


@suite
class ConcreteTestSuite extends TestSuiteBaseWithContainer {

  @before
  before() {
     this.catsService = TestSuiteBaseWIthContainer.container.get<CatsService>(CatsService);
     // ...
  }
}
```

Perhaps you can give that one a try.

Otherwise, and with Typescript, there is https://medium.com/better-programming/typescripts-new-top-level-await-cc6beadbde8
which might be just what you want.

**Comment by silkentrance** [comment]
As for chaining of before/after, see ***Static Lifecycle Hook Chaining*** in https://testdeck.org/pages/guide/inheritance

**Comment by silkentrance** [comment]
As for doing this the registerDI way, I so no way how this could be done so that the container is set up before that the first tests are being run, eventually leading to failing tests under certain conditions (container set up takes longer etc.).

**Comment by silkentrance** [comment]
@stevefan1999-personal have you had any luck with this or can you provide us with some feedback? otherwise we will close this.

**Comment by silkentrance** [comment]
closing since we had not heard back from @stevefan1999-personal
