### ISSUE TITLE
[FEATURE] - ESM support

### ISSUE THREAD

**Issue by saviski** [testdeck/testdeck#283]
## Description

Add support for importing from ESM Modules, something like this would work

### esm.d.ts
```typescript
export { only, params, pending, retries, runner, skip, slow, suite, test, timeout } from '@testdeck/mocha'
```

### esm.js
```javascript
import testdeck from '@testdeck/mocha'

export const only = testdeck.only
export const params = testdeck.params
export const pending = testdeck.pending
export const retries = testdeck.retries
export const runner = testdeck.runner
export const skip = testdeck.skip
export const slow = testdeck.slow
export const suite = testdeck.suite
export const test = testdeck.test
export const timeout = testdeck.timeout
```

Then you can write this code and it works if your `package.json` has `"type": "module"`

```typescript
import { suite, test } from '@testdeck/mocha/esm.js'

// tests go here
```

also having `"esModuleInterop": true` in tsconfig.json

**Comment by silkentrance** [comment]
for reference https://dev.to/iggredible/what-the-heck-are-cjs-amd-umd-and-esm-ikm

**Comment by pana-cc** [comment]
@saviski you look like you know what you are doing, do you know if we can make it backward and esm compatible in the index.ts directly?

Like we currently have:
``` TypeScript
const mochaDecorators = new MochaClassTestUI();
export = mochaDecorators;
```

If we reword it as:
``` TypeScript
export const only = mochaDecorators.only.bind(mochaDecorators);
// .. etc.
export default mochaDecorators;
```

Would it work with `"esModuleInterop": true` and `import { suite, test } from '@testdeck/mocha'?
If that's ok, I'll make a short work of it.

**Comment by pana-cc** [comment]
I made a small prototype and it seams to work. We won't even .bind as these are fields. If necessary we will bind them when assigning them in the base class.

There is a side glitch when using `@test` with fresh typescript version:
```
Unable to resolve signature of method decorator when called as an expression.
  Type 'MethodDecorator' has no properties in common with type 'TypedPropertyDescriptor<() => void>'.
```
I think the signature of the decorators had changed, I think it used to be ProeprtyDescriptor and these are no longer compatible. Needs update.

**Comment by pana-cc** [comment]
These should be ESM friendly: https://github.com/testdeck/testdeck/pull/287

**Comment by pana-cc** [comment]
Hi all,
There is a v0.2.0 that I just published. Give it a go. My publishing skills were a bit rusty. The imports have been reorganized. Please let me know if ESM is still broken in your scenarios.
Thanks,

**Comment by pana-cc** [comment]
@silkentrance Can we close this as well?
