### ISSUE TITLE
[FEATURE] - Allow for ordering of tests

### ISSUE THREAD

**Issue by rafaelliu** [testdeck/testdeck#291]
## Testdeck Version

0.2.0

## Description

Express dependency between tests are helpful to better organize tests and get more fine granular results out of tests. I has hopping to be able to some something like this:

```
@suite
class TestSuite {
    @test(id="1")
    function test1() {}

    @test(after="1")
    function test2() {}
}
```

It should probably be possible to use the function key too and do something like `@test({ after: this.test1 })` which would be more concise and possibly, refactory-friendly.

**Comment by silkentrance** [comment]
Hm, why don't you just move common preconditions and tests into a separate, non test annotated method of your test suite class or some other helper class?

This is reusable and none of your actual test cases will have dependencies towards other test cases, which is actually good test case design.

**Comment by silkentrance** [comment]
I for my part do not want to support such a feature as it introduces dependencies between test cases, that when run in parallel will lead to unwanted errors.
