### ISSUE TITLE
Existing packages do not use @testdeck/core latest

### ISSUE THREAD

**Issue by silkentrance** [testdeck/testdeck#301]
WIP

**Comment by adaliszk** [comment]
Probably https://github.com/dependabot can help you out here by automating the package updates.

**Comment by panayot-cankov** [comment]
I may have ruined the versioning. I think I updated the mocha to use the latest version of core to fix its typings. And the rest of the frameworks do not expose a test context like mocha. I think @silkentrance set up the lerna maybe it has a release workflow that would update package versions and publish? @silkentrance could we get some CONTRIBUTORS.md with release steps for the maintainers?

**Comment by pana-cc** [comment]
I fixed the versions, and used the `npm run lerna-publish` to release the DI fix. The versions should now be in order.
