### ISSUE TITLE
[BUG] - @testdeck/vitest is relying on commonjs module

### ISSUE THREAD

**Issue by Lukinoh** [testdeck/testdeck#322]
## Testdeck Version

0.3.0

## Testdeck Package

 - [x] `@testdeck/vite`

## NodeJS Version

 - [x] 18

## Mocha / Jasmine / Jest / Vitest Version

 - Vitest: 0.24.5

### Operating System

 - [x] Other: WSL2

### Actual Behaviour

I tried to use @testdeck/vitest on a small project, but it does not work because the build provided by testdeck is using commonjs, and vitest is not compatible with commonjs.

You can reproduce the issue easily on your repository by using the build output in your tests :

```bash
cd packages/vitest
sed -i 's/\.\/index/\.\/dist\/index.js/g' test.ts
npm run test
```

If you modify the `tsconfig.json` by
- Removing `"module": "commonjs"`
- Adding `"moduleResolution": "node"`

It will work, in your tests.

### Expected Behaviour

It should not rely on commonjs, otherwise, it won't work natively with vitest.

**Comment by silkentrance** [comment]
@Lukinoh Thank you very much for the quick feedback.

I have to look into this as testdeck is meant for being used in both the browser and node.

**Comment by silkentrance** [comment]
@Lukinoh Which version of vitest are you using? Looking at https://github.com/vitest-dev/vitest/issues/325 it seems as if this was already fixed.

**Comment by Lukinoh** [comment]
I made a typo in my ticket.
0.24.5 was the version of vitest not vite. I will change that.

You can find my small project with the bug here: https://stackblitz.com/edit/vitejs-vite-rqocxq?file=package.json

But concretely what seems to happen is that "@testdeck/vitest" loads the file [index.cjs of vite](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/index.cjs) which is empty.

**Comment by silkentrance** [comment]
I have looked into this.

Importing from ESM into CJS modules is quite tricky and requires a top level await, i.e.

```
const { expect } = await import("vitest");
```

While this works after the fact, i.e. the dist/index.js file is patched, it will not work when transpiling with tsc, as it requires `esnext` as its target and `esnext` for the module type. In addition it requires `moduleResolution` set to `node`.

**Comment by silkentrance** [comment]
Importing from CJS into ESM seems to be working, though.

**Comment by Lukinoh** [comment]
As vitest is thought to be ESM first, it would make sense to me.
